name: built_redux
version: 7.5.12
description:
  A state management library written in dart that enforces immutability
homepage: https://github.com/davidmarne/built_redux
dependencies:
  analyzer: '>=0.39.3 <0.42.0'
  build: ^1.2.2
  built_collection: ">=4.3.0 <=5.0.0-nullsafety.0"
  built_value: '>=7.0.8 <=8.0.0-nullsafety.0'
  source_gen: ^0.9.4+6
  test: ^1.9.1

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^1.2.0
  built_value_generator: ">=7.0.0 <=8.0.0-nullsafety.0"
  build_web_compilers: ^2.7.1
  workiva_analysis_options: ^1.0.0

environment:
  sdk: '>=2.4.0 <3.0.0'
